---
title: Kyle
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: redcarpet
highlighter: pygments
permalink: pretty
tagline: Cold Pizza Online is a blog by Kyle Roderick
description: Product at <a href="http://untappd.com" target="_blank">Untappd</a> and
  Podcaster at <a href="https://goodstuff.fm" target="_blank">Goodstuff</a>.
url: https://coldpizza.online
baseurl: "/"
author:
  name: Kyle Roderick
  url: https://mastodon.social/@kyle
paginate: 5
version: 0.1
github:
  repo: https://github.com/poole/hyde
