---
title: coldpizza.online
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: redcarpet
highlighter: pygments
permalink: pretty
tagline: Posts by Kyle Roderick
description: Posts by Kyle Roderick
url: https://coldpizza.online
twitter: https://twitter.com/hopburps
mastodon: https://mastodon.social/@kyle
podcasts: https://goodstuff.fm
baseurl: /
author:
  name: Kyle Roderick
  url: https://mastodon.social/@kyle
paginate: 5
version: 0.1
plugins:
  - jekyll-feed
